### ISSUE TITLE
Changes of May 30 1p3a server updates

### ISSUE THREAD

**Issue by Hanyang-Li** [tingyincc/auto_1p3a#1]
Maybe this is a change from May 30, I found that `qdmode` of check in request is not 2 (but 1), when we write our own `todaysay`. This doesn't affect us from getting points :), however, this may let the server know you are using bot to check in.

I read your code, in `punch` function, you assumed 2 cases, whether having code or not. So that means from May 30, we may need to fill in verify code, whereas not always having it, and sometimes we are not asked to recognize verify code?

**Comment by tingyincc** [comment]
Yes you are right. I wrote two cases to handle it.
Thanks for noting `qdmode` . I will try to use 1 to see if the server unblock me!
